package com.fscon.pojo;

import java.io.Serializable;

public class HomeworkImage implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework_image.homework_image_id
     *
     * @mbg.generated
     */
    private Integer homeworkImageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework_image.homework_id
     *
     * @mbg.generated
     */
    private Integer homeworkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework_image.homework_image_path
     *
     * @mbg.generated
     */
    private String homeworkImagePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table homework_image
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_image
     *
     * @mbg.generated
     */
    public HomeworkImage(Integer homeworkImageId, Integer homeworkId, String homeworkImagePath) {
        this.homeworkImageId = homeworkImageId;
        this.homeworkId = homeworkId;
        this.homeworkImagePath = homeworkImagePath;
    }

    public HomeworkImage(Integer homeworkId, String homeworkImagePath) {
        this.homeworkId = homeworkId;
        this.homeworkImagePath = homeworkImagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_image
     *
     * @mbg.generated
     */
    public HomeworkImage() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework_image.homework_image_id
     *
     * @return the value of homework_image.homework_image_id
     *
     * @mbg.generated
     */
    public Integer getHomeworkImageId() {
        return homeworkImageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework_image.homework_image_id
     *
     * @param homeworkImageId the value for homework_image.homework_image_id
     *
     * @mbg.generated
     */
    public void setHomeworkImageId(Integer homeworkImageId) {
        this.homeworkImageId = homeworkImageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework_image.homework_id
     *
     * @return the value of homework_image.homework_id
     *
     * @mbg.generated
     */
    public Integer getHomeworkId() {
        return homeworkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework_image.homework_id
     *
     * @param homeworkId the value for homework_image.homework_id
     *
     * @mbg.generated
     */
    public void setHomeworkId(Integer homeworkId) {
        this.homeworkId = homeworkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework_image.homework_image_path
     *
     * @return the value of homework_image.homework_image_path
     *
     * @mbg.generated
     */
    public String getHomeworkImagePath() {
        return homeworkImagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework_image.homework_image_path
     *
     * @param homeworkImagePath the value for homework_image.homework_image_path
     *
     * @mbg.generated
     */
    public void setHomeworkImagePath(String homeworkImagePath) {
        this.homeworkImagePath = homeworkImagePath == null ? null : homeworkImagePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_image
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        HomeworkImage other = (HomeworkImage) that;
        return (this.getHomeworkImageId() == null ? other.getHomeworkImageId() == null : this.getHomeworkImageId().equals(other.getHomeworkImageId()))
            && (this.getHomeworkId() == null ? other.getHomeworkId() == null : this.getHomeworkId().equals(other.getHomeworkId()))
            && (this.getHomeworkImagePath() == null ? other.getHomeworkImagePath() == null : this.getHomeworkImagePath().equals(other.getHomeworkImagePath()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_image
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getHomeworkImageId() == null) ? 0 : getHomeworkImageId().hashCode());
        result = prime * result + ((getHomeworkId() == null) ? 0 : getHomeworkId().hashCode());
        result = prime * result + ((getHomeworkImagePath() == null) ? 0 : getHomeworkImagePath().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_image
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", homeworkImageId=").append(homeworkImageId);
        sb.append(", homeworkId=").append(homeworkId);
        sb.append(", homeworkImagePath=").append(homeworkImagePath);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}