package com.fscon.dao;

import com.fscon.pojo.Homework;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface HomeworkMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer homeworkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework
     *
     * @mbg.generated
     */
    int insert(Homework record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework
     *
     * @mbg.generated
     */
    int insertSelective(Homework record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework
     *
     * @mbg.generated
     */
    Homework selectByPrimaryKey(Integer homeworkId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Homework record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Homework record);

    int addHomework(Homework record);

    List<Homework> selectHomeworkByClassId(Integer classId, RowBounds rowBounds);

    List<Homework> selectHomeworkByTeacherId(Integer teacherId, RowBounds rowBounds);
}