package com.fscon.dao;

import com.fscon.pojo.HomeworkVoice;

import java.util.List;

public interface HomeworkVoiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_voice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer homeworkVoiceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_voice
     *
     * @mbg.generated
     */
    int insert(HomeworkVoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_voice
     *
     * @mbg.generated
     */
    int insertSelective(HomeworkVoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_voice
     *
     * @mbg.generated
     */
    HomeworkVoice selectByPrimaryKey(Integer homeworkVoiceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_voice
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HomeworkVoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_voice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HomeworkVoice record);

    int addHomeworkVoice(List<HomeworkVoice> homeworkVoiceList);

    List<HomeworkVoice> selectHomeworkVoiceByHomeworkId(Integer homeworkId);

    int updateBatch(List<HomeworkVoice> homeworkVoiceList);

    int deleteBatch(List<HomeworkVoice> homeworkVoiceList);
}