package com.fscon.dao;

import com.fscon.pojo.MomentImage;

import java.util.List;

public interface MomentImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moment_image
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer momentImageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moment_image
     *
     * @mbg.generated
     */
    int insert(MomentImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moment_image
     *
     * @mbg.generated
     */
    int insertSelective(MomentImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moment_image
     *
     * @mbg.generated
     */
    MomentImage selectByPrimaryKey(Integer momentImageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moment_image
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MomentImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table moment_image
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(MomentImage record);

    int addMomentImage(List<MomentImage> momentImageList);

    List<MomentImage> selectMomentImageByMomentId(Integer momentId);

    int updateBatch(List<MomentImage> momentImageList);

    int deleteBatch(List<MomentImage> momentImageList);
}