package com.fscon.dao;

import com.fscon.pojo.NoticeVoice;

import java.util.List;

public interface NoticeVoiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_voice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer noticeVoiceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_voice
     *
     * @mbg.generated
     */
    int insert(NoticeVoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_voice
     *
     * @mbg.generated
     */
    int insertSelective(NoticeVoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_voice
     *
     * @mbg.generated
     */
    NoticeVoice selectByPrimaryKey(Integer noticeVoiceId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_voice
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(NoticeVoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_voice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(NoticeVoice record);

    int addNoticeVoice(List<NoticeVoice> noticeVoiceList);

    List<NoticeVoice> selectNoticeVoiceByNoticeId(Integer noticeId);

    int updateBatch(List<NoticeVoice> noticeVoiceList);

    int deleteBatch(List<NoticeVoice> noticeVoiceList);
}