package com.fscon.dao;

import com.fscon.pojo.NoticeImage;

import java.util.List;

public interface NoticeImageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_image
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer noticeImageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_image
     *
     * @mbg.generated
     */
    int insert(NoticeImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_image
     *
     * @mbg.generated
     */
    int insertSelective(NoticeImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_image
     *
     * @mbg.generated
     */
    NoticeImage selectByPrimaryKey(Integer noticeImageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_image
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(NoticeImage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_image
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(NoticeImage record);

    int addNoticeImage(List<NoticeImage> noticeImageList);

    List<NoticeImage> selectNoticeImageByNoticeId(Integer noticeId);

    int updateBatch(List<NoticeImage> noticeImageList);

    int deleteBatch(List<NoticeImage> noticeImageList);

}