package com.fscon.dao;

import com.fscon.pojo.Parent;
import org.apache.ibatis.annotations.Param;

public interface ParentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer parentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent
     *
     * @mbg.generated
     */
    int insert(Parent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent
     *
     * @mbg.generated
     */
    int insertSelective(Parent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent
     *
     * @mbg.generated
     */
    Parent selectByPrimaryKey(Integer parentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Parent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Parent record);

    Parent login(@Param("parentTelephone")String parentTelephone, @Param("parentPassword")String parentPassword);

    int register(Parent parent);

    Parent selectByParentTelephone(String parentTelephone);
}