package com.fscon.dao;

import com.fscon.pojo.StudentParent;

public interface StudentParentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_parent
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_parent
     *
     * @mbg.generated
     */
    int insert(StudentParent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_parent
     *
     * @mbg.generated
     */
    int insertSelective(StudentParent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_parent
     *
     * @mbg.generated
     */
    StudentParent selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_parent
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(StudentParent record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table student_parent
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(StudentParent record);
}