package com.fscon.dao;

import com.fscon.pojo.TeacherSubject;

import java.util.List;

public interface TeacherSubjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_subject
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_subject
     *
     * @mbg.generated
     */
    int insert(TeacherSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_subject
     *
     * @mbg.generated
     */
    int insertSelective(TeacherSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_subject
     *
     * @mbg.generated
     */
    TeacherSubject selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_subject
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(TeacherSubject record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher_subject
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(TeacherSubject record);

    List<TeacherSubject> selectTeacherSubjectByNoticeId(Integer teacherId);
}