package com.jaron.fsconnect.bean;

import java.io.Serializable;

public class NoticeImage implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_image.notice_image_id
     *
     * @mbg.generated
     */
    private Integer noticeImageId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_image.notice_id
     *
     * @mbg.generated
     */
    private Integer noticeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column notice_image.notice_image_path
     *
     * @mbg.generated
     */
    private String noticeImagePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table notice_image
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_image
     *
     * @mbg.generated
     */
    public NoticeImage(Integer noticeImageId, Integer noticeId, String noticeImagePath) {
        this.noticeImageId = noticeImageId;
        this.noticeId = noticeId;
        this.noticeImagePath = noticeImagePath;
    }

    public NoticeImage(Integer noticeId, String noticeImagePath) {
        this.noticeId = noticeId;
        this.noticeImagePath = noticeImagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_image
     *
     * @mbg.generated
     */
    public NoticeImage() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_image.notice_image_id
     *
     * @return the value of notice_image.notice_image_id
     *
     * @mbg.generated
     */
    public Integer getNoticeImageId() {
        return noticeImageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_image.notice_image_id
     *
     * @param noticeImageId the value for notice_image.notice_image_id
     *
     * @mbg.generated
     */
    public void setNoticeImageId(Integer noticeImageId) {
        this.noticeImageId = noticeImageId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_image.notice_id
     *
     * @return the value of notice_image.notice_id
     *
     * @mbg.generated
     */
    public Integer getNoticeId() {
        return noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_image.notice_id
     *
     * @param noticeId the value for notice_image.notice_id
     *
     * @mbg.generated
     */
    public void setNoticeId(Integer noticeId) {
        this.noticeId = noticeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column notice_image.notice_image_path
     *
     * @return the value of notice_image.notice_image_path
     *
     * @mbg.generated
     */
    public String getNoticeImagePath() {
        return noticeImagePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column notice_image.notice_image_path
     *
     * @param noticeImagePath the value for notice_image.notice_image_path
     *
     * @mbg.generated
     */
    public void setNoticeImagePath(String noticeImagePath) {
        this.noticeImagePath = noticeImagePath == null ? null : noticeImagePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_image
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        NoticeImage other = (NoticeImage) that;
        return (this.getNoticeImageId() == null ? other.getNoticeImageId() == null : this.getNoticeImageId().equals(other.getNoticeImageId()))
            && (this.getNoticeId() == null ? other.getNoticeId() == null : this.getNoticeId().equals(other.getNoticeId()))
            && (this.getNoticeImagePath() == null ? other.getNoticeImagePath() == null : this.getNoticeImagePath().equals(other.getNoticeImagePath()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_image
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getNoticeImageId() == null) ? 0 : getNoticeImageId().hashCode());
        result = prime * result + ((getNoticeId() == null) ? 0 : getNoticeId().hashCode());
        result = prime * result + ((getNoticeImagePath() == null) ? 0 : getNoticeImagePath().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table notice_image
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", noticeImageId=").append(noticeImageId);
        sb.append(", noticeId=").append(noticeId);
        sb.append(", noticeImagePath=").append(noticeImagePath);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}