package com.jaron.fsconnectparent.bean;

import java.io.Serializable;

public class HomeworkVoice implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework_voice.homework_voice_id
     *
     * @mbg.generated
     */
    private Integer homeworkVoiceId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework_voice.homework_id
     *
     * @mbg.generated
     */
    private Integer homeworkId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column homework_voice.homework_voice_path
     *
     * @mbg.generated
     */
    private String homeworkVoicePath;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table homework_voice
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_voice
     *
     * @mbg.generated
     */
    public HomeworkVoice(Integer homeworkVoiceId, Integer homeworkId, String homeworkVoicePath) {
        this.homeworkVoiceId = homeworkVoiceId;
        this.homeworkId = homeworkId;
        this.homeworkVoicePath = homeworkVoicePath;
    }

    public HomeworkVoice(Integer homeworkId, String homeworkVoicePath) {
        this.homeworkId = homeworkId;
        this.homeworkVoicePath = homeworkVoicePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_voice
     *
     * @mbg.generated
     */
    public HomeworkVoice() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework_voice.homework_voice_id
     *
     * @return the value of homework_voice.homework_voice_id
     *
     * @mbg.generated
     */
    public Integer getHomeworkVoiceId() {
        return homeworkVoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework_voice.homework_voice_id
     *
     * @param homeworkVoiceId the value for homework_voice.homework_voice_id
     *
     * @mbg.generated
     */
    public void setHomeworkVoiceId(Integer homeworkVoiceId) {
        this.homeworkVoiceId = homeworkVoiceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework_voice.homework_id
     *
     * @return the value of homework_voice.homework_id
     *
     * @mbg.generated
     */
    public Integer getHomeworkId() {
        return homeworkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework_voice.homework_id
     *
     * @param homeworkId the value for homework_voice.homework_id
     *
     * @mbg.generated
     */
    public void setHomeworkId(Integer homeworkId) {
        this.homeworkId = homeworkId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column homework_voice.homework_voice_path
     *
     * @return the value of homework_voice.homework_voice_path
     *
     * @mbg.generated
     */
    public String getHomeworkVoicePath() {
        return homeworkVoicePath;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column homework_voice.homework_voice_path
     *
     * @param homeworkVoicePath the value for homework_voice.homework_voice_path
     *
     * @mbg.generated
     */
    public void setHomeworkVoicePath(String homeworkVoicePath) {
        this.homeworkVoicePath = homeworkVoicePath == null ? null : homeworkVoicePath.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_voice
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        HomeworkVoice other = (HomeworkVoice) that;
        return (this.getHomeworkVoiceId() == null ? other.getHomeworkVoiceId() == null : this.getHomeworkVoiceId().equals(other.getHomeworkVoiceId()))
            && (this.getHomeworkId() == null ? other.getHomeworkId() == null : this.getHomeworkId().equals(other.getHomeworkId()))
            && (this.getHomeworkVoicePath() == null ? other.getHomeworkVoicePath() == null : this.getHomeworkVoicePath().equals(other.getHomeworkVoicePath()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_voice
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getHomeworkVoiceId() == null) ? 0 : getHomeworkVoiceId().hashCode());
        result = prime * result + ((getHomeworkId() == null) ? 0 : getHomeworkId().hashCode());
        result = prime * result + ((getHomeworkVoicePath() == null) ? 0 : getHomeworkVoicePath().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table homework_voice
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", homeworkVoiceId=").append(homeworkVoiceId);
        sb.append(", homeworkId=").append(homeworkId);
        sb.append(", homeworkVoicePath=").append(homeworkVoicePath);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}