package com.jaron.fsconnectparent.bean;

import java.io.Serializable;

public class Parent implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent.parent_id
     *
     * @mbg.generated
     */
    private Integer parentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent.parent_telephone
     *
     * @mbg.generated
     */
    private String parentTelephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent.parent_username
     *
     * @mbg.generated
     */
    private String parentUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent.parent_password
     *
     * @mbg.generated
     */
    private String parentPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent.parent_turename
     *
     * @mbg.generated
     */
    private String parentTruename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent.sex
     *
     * @mbg.generated
     */
    private Integer sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column parent.head_icon
     *
     * @mbg.generated
     */
    private String headIcon;

    private Integer studentID;

    private Student student;

    private String cookie;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table parent
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent
     *
     * @mbg.generated
     */
    public Parent(Integer parentId, String parentTelephone, String parentUsername, String parentPassword, String parentTruename, Integer sex, String headIcon,Integer studentID) {
        this.parentId = parentId;
        this.parentTelephone = parentTelephone;
        this.parentUsername = parentUsername;
        this.parentPassword = parentPassword;
        this.parentTruename = parentTruename;
        this.sex = sex;
        this.headIcon = headIcon;
        this.studentID=studentID;
    }

    public Parent(String parentTelephone, String parentUsername,String parentTruename) {
        this.parentTelephone = parentTelephone;
        this.parentUsername = parentUsername;
        this.parentTruename=parentTruename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent
     *
     * @mbg.generated
     */
    public Parent() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent.parent_id
     *
     * @return the value of parent.parent_id
     *
     * @mbg.generated
     */
    public Integer getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent.parent_id
     *
     * @param parentId the value for parent.parent_id
     *
     * @mbg.generated
     */
    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent.parent_telephone
     *
     * @return the value of parent.parent_telephone
     *
     * @mbg.generated
     */
    public String getParentTelephone() {
        return parentTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent.parent_telephone
     *
     * @param parentTelephone the value for parent.parent_telephone
     *
     * @mbg.generated
     */
    public void setParentTelephone(String parentTelephone) {
        this.parentTelephone = parentTelephone == null ? null : parentTelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent.parent_username
     *
     * @return the value of parent.parent_username
     *
     * @mbg.generated
     */
    public String getParentUsername() {
        return parentUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent.parent_username
     *
     * @param parentUsername the value for parent.parent_username
     *
     * @mbg.generated
     */
    public void setParentUsername(String parentUsername) {
        this.parentUsername = parentUsername == null ? null : parentUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent.parent_password
     *
     * @return the value of parent.parent_password
     *
     * @mbg.generated
     */
    public String getParentPassword() {
        return parentPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent.parent_password
     *
     * @param parentPassword the value for parent.parent_password
     *
     * @mbg.generated
     */
    public void setParentPassword(String parentPassword) {
        this.parentPassword = parentPassword == null ? null : parentPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent.parent_turename
     *
     * @return the value of parent.parent_turename
     *
     * @mbg.generated
     */
    public String getParentTruename() {
        return parentTruename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent.parent_turename
     *
     * @param parentTruename the value for parent.parent_turename
     *
     * @mbg.generated
     */
    public void setParentTruename(String parentTruename) {
        this.parentTruename = parentTruename == null ? null : parentTruename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent.sex
     *
     * @return the value of parent.sex
     *
     * @mbg.generated
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent.sex
     *
     * @param sex the value for parent.sex
     *
     * @mbg.generated
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column parent.head_icon
     *
     * @return the value of parent.head_icon
     *
     * @mbg.generated
     */
    public String getHeadIcon() {
        return headIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column parent.head_icon
     *
     * @param headIcon the value for parent.head_icon
     *
     * @mbg.generated
     */
    public void setHeadIcon(String headIcon) {
        this.headIcon = headIcon == null ? null : headIcon.trim();
    }

    public Integer getStudentID() {
        return studentID;
    }

    public void setStudentID(Integer studentID) {
        this.studentID = studentID;
    }

    public Student getStudent() {
        return student;
    }

    public void setStudent(Student student) {
        this.student = student;
    }

    public String getCookie() {
        return cookie;
    }

    public void setCookie(String cookie) {
        this.cookie = cookie;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Parent other = (Parent) that;
        return (this.getParentId() == null ? other.getParentId() == null : this.getParentId().equals(other.getParentId()))
                && (this.getParentTelephone() == null ? other.getParentTelephone() == null : this.getParentTelephone().equals(other.getParentTelephone()))
                && (this.getParentUsername() == null ? other.getParentUsername() == null : this.getParentUsername().equals(other.getParentUsername()))
                && (this.getParentPassword() == null ? other.getParentPassword() == null : this.getParentPassword().equals(other.getParentPassword()))
                && (this.getParentTruename() == null ? other.getParentTruename() == null : this.getParentTruename().equals(other.getParentTruename()))
                && (this.getSex() == null ? other.getSex() == null : this.getSex().equals(other.getSex()))
                && (this.getHeadIcon() == null ? other.getHeadIcon() == null : this.getHeadIcon().equals(other.getHeadIcon()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getParentId() == null) ? 0 : getParentId().hashCode());
        result = prime * result + ((getParentTelephone() == null) ? 0 : getParentTelephone().hashCode());
        result = prime * result + ((getParentUsername() == null) ? 0 : getParentUsername().hashCode());
        result = prime * result + ((getParentPassword() == null) ? 0 : getParentPassword().hashCode());
        result = prime * result + ((getParentTruename() == null) ? 0 : getParentTruename().hashCode());
        result = prime * result + ((getSex() == null) ? 0 : getSex().hashCode());
        result = prime * result + ((getHeadIcon() == null) ? 0 : getHeadIcon().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table parent
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", parentId=").append(parentId);
        sb.append(", parentTelephone=").append(parentTelephone);
        sb.append(", parentUsername=").append(parentUsername);
        sb.append(", parentPassword=").append(parentPassword);
        sb.append(", parentTruename=").append(parentTruename);
        sb.append(", sex=").append(sex);
        sb.append(", headIcon=").append(headIcon);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}