package com.jaron.fsconnectparent.bean;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

public class Teacher implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teacher_id
     *
     * @mbg.generated
     */
    private Integer teacherId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teacher_telephone
     *
     * @mbg.generated
     */
    private String teacherTelephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teacher_username
     *
     * @mbg.generated
     */
    private String teacherUsername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teacher_password
     *
     * @mbg.generated
     */
    private String teacherPassword;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teacher_truename
     *
     * @mbg.generated
     */
    private String teacherTruename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.teacher_sex
     *
     * @mbg.generated
     */
    private Integer teacherSex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.major
     *
     * @mbg.generated
     */
    private String major;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.head_icon
     *
     * @mbg.generated
     */
    private String headIcon;

    private String cookie;

    private ArrayList<TeacherSubject> teacherSubjectList=null;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table teacher
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated
     */
    public Teacher(Integer teacherId, String teacherTelephone, String teacherUsername, String teacherPassword, String teacherTruename, Integer teacherSex, String major, String headIcon) {
        this.teacherId = teacherId;
        this.teacherTelephone = teacherTelephone;
        this.teacherUsername = teacherUsername;
        this.teacherPassword = teacherPassword;
        this.teacherTruename = teacherTruename;
        this.teacherSex = teacherSex;
        this.major = major;
        this.headIcon = headIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated
     */
    public Teacher() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teacher_id
     *
     * @return the value of teacher.teacher_id
     *
     * @mbg.generated
     */
    public Integer getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teacher_id
     *
     * @param teacherId the value for teacher.teacher_id
     *
     * @mbg.generated
     */
    public void setTeacherId(Integer teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teacher_telephone
     *
     * @return the value of teacher.teacher_telephone
     *
     * @mbg.generated
     */
    public String getTeacherTelephone() {
        return teacherTelephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teacher_telephone
     *
     * @param teacherTelephone the value for teacher.teacher_telephone
     *
     * @mbg.generated
     */
    public void setTeacherTelephone(String teacherTelephone) {
        this.teacherTelephone = teacherTelephone == null ? null : teacherTelephone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teacher_username
     *
     * @return the value of teacher.teacher_username
     *
     * @mbg.generated
     */
    public String getTeacherUsername() {
        return teacherUsername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teacher_username
     *
     * @param teacherUsername the value for teacher.teacher_username
     *
     * @mbg.generated
     */
    public void setTeacherUsername(String teacherUsername) {
        this.teacherUsername = teacherUsername == null ? null : teacherUsername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teacher_password
     *
     * @return the value of teacher.teacher_password
     *
     * @mbg.generated
     */
    public String getTeacherPassword() {
        return teacherPassword;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teacher_password
     *
     * @param teacherPassword the value for teacher.teacher_password
     *
     * @mbg.generated
     */
    public void setTeacherPassword(String teacherPassword) {
        this.teacherPassword = teacherPassword == null ? null : teacherPassword.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teacher_truename
     *
     * @return the value of teacher.teacher_truename
     *
     * @mbg.generated
     */
    public String getTeacherTruename() {
        return teacherTruename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teacher_truename
     *
     * @param teacherTruename the value for teacher.teacher_truename
     *
     * @mbg.generated
     */
    public void setTeacherTruename(String teacherTruename) {
        this.teacherTruename = teacherTruename == null ? null : teacherTruename.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.teacher_sex
     *
     * @return the value of teacher.teacher_sex
     *
     * @mbg.generated
     */
    public Integer getTeacherSex() {
        return teacherSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.teacher_sex
     *
     * @param teacherSex the value for teacher.teacher_sex
     *
     * @mbg.generated
     */
    public void setTeacherSex(Integer teacherSex) {
        this.teacherSex = teacherSex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.major
     *
     * @return the value of teacher.major
     *
     * @mbg.generated
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.major
     *
     * @param major the value for teacher.major
     *
     * @mbg.generated
     */
    public void setMajor(String major) {
        this.major = major == null ? null : major.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.head_icon
     *
     * @return the value of teacher.head_icon
     *
     * @mbg.generated
     */
    public String getHeadIcon() {
        return headIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.head_icon
     *
     * @param headIcon the value for teacher.head_icon
     *
     * @mbg.generated
     */
    public void setHeadIcon(String headIcon) {
        this.headIcon = headIcon == null ? null : headIcon.trim();
    }

    public String getCookie() {
        return cookie;
    }

    public void setCookie(String cookie) {
        this.cookie = cookie;
    }

    public List<TeacherSubject> getTeacherSubjectList() {
        return teacherSubjectList;
    }

    public void setTeacherSubjectList(ArrayList<TeacherSubject> teacherSubjectList) {
        this.teacherSubjectList = teacherSubjectList;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated
     */
    @Override
    public boolean equals(Object that) {
        if (this == that) {
            return true;
        }
        if (that == null) {
            return false;
        }
        if (getClass() != that.getClass()) {
            return false;
        }
        Teacher other = (Teacher) that;
        return (this.getTeacherId() == null ? other.getTeacherId() == null : this.getTeacherId().equals(other.getTeacherId()))
                && (this.getTeacherTelephone() == null ? other.getTeacherTelephone() == null : this.getTeacherTelephone().equals(other.getTeacherTelephone()))
                && (this.getTeacherUsername() == null ? other.getTeacherUsername() == null : this.getTeacherUsername().equals(other.getTeacherUsername()))
                && (this.getTeacherPassword() == null ? other.getTeacherPassword() == null : this.getTeacherPassword().equals(other.getTeacherPassword()))
                && (this.getTeacherTruename() == null ? other.getTeacherTruename() == null : this.getTeacherTruename().equals(other.getTeacherTruename()))
                && (this.getTeacherSex() == null ? other.getTeacherSex() == null : this.getTeacherSex().equals(other.getTeacherSex()))
                && (this.getMajor() == null ? other.getMajor() == null : this.getMajor().equals(other.getMajor()))
                && (this.getHeadIcon() == null ? other.getHeadIcon() == null : this.getHeadIcon().equals(other.getHeadIcon()));
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((getTeacherId() == null) ? 0 : getTeacherId().hashCode());
        result = prime * result + ((getTeacherTelephone() == null) ? 0 : getTeacherTelephone().hashCode());
        result = prime * result + ((getTeacherUsername() == null) ? 0 : getTeacherUsername().hashCode());
        result = prime * result + ((getTeacherPassword() == null) ? 0 : getTeacherPassword().hashCode());
        result = prime * result + ((getTeacherTruename() == null) ? 0 : getTeacherTruename().hashCode());
        result = prime * result + ((getTeacherSex() == null) ? 0 : getTeacherSex().hashCode());
        result = prime * result + ((getMajor() == null) ? 0 : getMajor().hashCode());
        result = prime * result + ((getHeadIcon() == null) ? 0 : getHeadIcon().hashCode());
        return result;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table teacher
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", teacherId=").append(teacherId);
        sb.append(", teacherTelephone=").append(teacherTelephone);
        sb.append(", teacherUsername=").append(teacherUsername);
        sb.append(", teacherPassword=").append(teacherPassword);
        sb.append(", teacherTruename=").append(teacherTruename);
        sb.append(", teacherSex=").append(teacherSex);
        sb.append(", major=").append(major);
        sb.append(", headIcon=").append(headIcon);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}